version: "3.8"

services:
  app:
    build: .
    ports:
      - "7272:7272"
    environment:
      - MONGO_URI=mongodb://mongo:27017/quizapp
      - NODE_ENV=development
      - API_VERSION=0.0.1
      - PORT=7272
      - JWT_SECRET=ASDASDASDKJSDCKFLJAESICKAEOLKCFSDE
      - JWT_EXPIRE=90d
      - JWT_EXPIRE_N=90
  mongo:
    image: mongo
    ports:
      - "27017:27017"